{
 "title": "Cost Explorer-Main",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Account",
    "label": "Account",
    "query": "{\"find\":\"terms\",\"field\":\"Budget.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Cloud Governance Nightly Cost Report",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "options": {
    "content": "\n![Cloud Governance](https://github.com/redhat-performance/cloud-governance/blob/main/images/cloud_governance.png?raw=true \"Tooltip Text\")\n"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": {
    "content": "![AWS](https://pbs.twimg.com/profile_images/1402754057245138947/Yz4xMoJC_400x400.jpg \"Tooltip Text\")\n"
   }
  },
  {
   "title": "Cost Per Account",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost Per Account: $Account",
     "type": "barchart",
     "description": "Show last 2 days for showing final cost",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Budget.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Budget: $Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Budget.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "max" }
       ],
       "query": "Budget: $Account",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Account Charge Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Account Charge Type",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ChargeType.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Budget: $Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$Account Charge Type",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ChargeType.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Budget: $Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$Account Charge Type",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ChargeType.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "max" }
       ],
       "query": "Budget: $Account",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "PurchaseTypes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Account Purchase Types",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "PurchaseType.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Budget.keyword= $Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$Account Purchase Types",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "PurchaseType.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "max" }
       ],
       "query": "Budget.keyword= $Account",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Cost Per Project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost Per Project: $Account",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Project.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Budget: $Account AND !NoTagKey AND !\"PERF-DEPT-REFUND\" AND !\"PERF-SCALE-REFUND\" AND !\"PSAP-REFUND\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$Account",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Project.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Budget: $Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$Account",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Project.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "max" }
       ],
       "query": "Budget=$Account AND !NoTagKey AND !\"PERF-DEPT-REFUND\" AND !\"PERF-SCALE-REFUND\" AND !\"PSAP-REFUND\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Cost Per Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost Per Manager: $Account",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Manager.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "max" }
       ],
       "query": "Budget=$Account AND !NoTagKey AND !\"PERF-DEPT-REFUND\" AND !\"PERF-SCALE-REFUND\" AND !\"PSAP-REFUND\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$Account",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Manager.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Budget=$Account ",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$Account",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Manager.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "max" }
       ],
       "query": "Budget=$Account AND !NoTagKey AND !\"PERF-DEPT-REFUND\" AND !\"PERF-SCALE-REFUND\" AND !\"PSAP-REFUND\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Cost Per Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost Per Users $Account",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "User.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Budget=$Account AND !NoTagKey AND !\"PERF-DEPT-REFUND\" AND !\"PERF-SCALE-REFUND\" AND !\"PSAP-REFUND\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$Account",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "User.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Budget=$Account AND !NoTagKey AND !\"PERF-SCALE-REFUND\" AND !\"PSAP-REFUND\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$Account",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "User.keyword",
         "id": "4",
         "settings": {
          "min_doc_count": "1",
          "missing": "User.keyword",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "settings": { "missing": "0" }, "type": "max" }
       ],
       "query": "Budget=$Account AND !NoTagKey AND !\"PERF-DEPT-REFUND\" AND !\"PERF-SCALE-REFUND\" AND !\"PSAP-REFUND\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Mail Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Monthly report",
     "type": "table",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "!\"notify_admin\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Monthly report",
     "type": "table",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 24 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Policy.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "MessageType.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Skip Policy Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Skip resources in $Account",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "Account=$Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Cost of skip resources in $Account",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Account.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Account=$Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Skip resources by User in $Account",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "User.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "Account=$Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Skip policy Resources in $Account",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 14, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ResourceName.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "Account.keyword=$Account",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy: EC2 Stop >= 30 days",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "EC2_Stop: $Account: ",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "region.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "count", "id": "1", "type": "max" }
       ],
       "query": "policy.keyword:\"ec2_stop\" AND account.keyword:$Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EC2_Stop: $Account: ",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ec2_stop.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "region.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "count", "id": "1", "type": "sum" }
       ],
       "query": "policy.keyword:\"ec2_stop\" AND account.keyword:$Account",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy: EC2-Idle >= 2 days",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "EC2 Idle: $Account",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "region.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "resources", "id": "1", "type": "sum" }
       ],
       "query": "policy.keyword:\"ec2_idle\" AND account.keyword:$Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "EC2 Idle: : $Account",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "resources_list.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "region.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "resources", "id": "1", "type": "sum" }
       ],
       "query": "account.keyword:$Account AND policy.keyword:\"ec2_idle\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "InstanceTypes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "InstancesTypes: $Account",
     "type": "barchart",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "instance_type.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "instance_count", "id": "1", "type": "sum" }
       ],
       "query": "account.keyword: $Account",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy: Empty Bucket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Empty Buckets: $Account",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "empty_buckets.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "account.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "count", "id": "1", "type": "min" }
       ],
       "query": "account.keyword:$Account",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy: Zombie & Empty Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zombie Snapshots",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "zombie_snapshots.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "account.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "region.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "count", "id": "1", "type": "max" }
       ],
       "query": "account.keyword=$Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Zombie NatGateways: $Account",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "zombie_nat_gateways.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "region.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "account.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "count", "id": "1", "type": "sum" }
       ],
       "query": "account.keyword=$Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Zombie ElasticIps",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "zombie_elastic_ips.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "account.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "region.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "count", "id": "1", "type": "max" }
       ],
       "query": "account.keyword=$Account",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Empty Roles",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "empty_roles.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "account.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "count", "id": "1", "type": "max" }
       ],
       "query": "account.keyword=$Account",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Email",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost Per Email: $Account",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Email.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Budget=$Account AND !NoTagKey AND !\"PERF-DEPT-REFUND\" AND !\"PERF-SCALE-REFUND\" AND !\"PSAP-REFUND\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Names",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost Per Resource  Names: $Account",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "Name.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "Cost", "id": "1", "type": "sum" }
       ],
       "query": "Budget.keyword: $Account AND !NoTagKey AND !\"PERF-DEPT-REFUND\" AND !\"PERF-SCALE-REFUND\" AND !\"PSAP-REFUND\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "User: missing tags",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pef-Dept: missing tags ",
     "type": "table",
     "description": "Spreadsheet tags",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "PSAP: missing tags ",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Perf-Scale: missing tags ",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}