{
 "title": "Payer Account Billing Reports",
 "description": "Forecasting for the Perf-Dept, Openshift-PerfScale, OPenshift-PSAP",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   {
    "name": "Owner",
    "label": "Owner",
    "query": "{\"find\":\"terms\", \"field\":\"Owner.keyword\"}"
   },
   {
    "name": "CostCenter",
    "label": "CostCenter",
    "query": "{\"find\":\"terms\", \"field\":\"CostCenter\", \"query\": \"Owner.keyword: $Owner\"}"
   },
   {
    "name": "CloudName",
    "label": "CloudName",
    "query": "{\"find\":\"terms\", \"field\":\"CloudName.keyword\", \"query\": \"CostCenter: $CostCenter AND Owner.keyword: $Owner\"}"
   },
   {
    "name": "Account",
    "label": "Account",
    "query": "{\"find\":\"terms\", \"field\":\"Account.keyword\",   \"query\": \"CloudName.keyword: $CloudName AND CostCenter: $CostCenter AND Owner.keyword: $Owner AND  !(AccountId.keyword=\\\"\\\") \" }"
   },
   {
    "name": "AccountId",
    "label": "AccountId",
    "query": "{\"find\":\"terms\", \"field\":\"AccountId.keyword\",   \"query\": \"CloudName.keyword: $CloudName AND CostCenter: $CostCenter AND Owner.keyword: $Owner AND  Account.keyword: $Account\"  }"
   },
   {
    "name": "Month",
    "label": "Month",
    "query": "{\"find\":\"terms\", \"field\":\"filter_date.keyword\", \"query\": \"Account.keyword: $Account AND CostCenter: $CostCenter AND CloudName: $CloudName\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Total $CloudName/ $Month",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Account.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "Actual",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "SavingsPlanCost",
       "id": "4",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "PremiumSupportFee",
       "id": "5",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Budget", "id": "1", "type": "sum" }
     ],
     "query": "(Account.keyword: $Account AND CostCenter: $CostCenter AND CloudName: $CloudName AND filter_date.keyword: $Month)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Actual $CloudName:  Cost / $Month",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "CloudName.keyword",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Actual", "id": "1", "settings": { "missing": "0" }, "type": "sum" },
      { "field": "SavingsPlanCost", "id": "3", "settings": { "missing": "0" }, "type": "sum" },
      { "field": "PremiumSupportFee", "id": "4", "settings": { "missing": "0" }, "type": "sum" }
     ],
     "query": "CloudName.keyword: $CloudName AND Owner.keyword: $Owner AND CostCenter: $CostCenter AND Account.keyword: $Account AND filter_date.keyword: $Month",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": " $Account Forecast, Budget, Actual / $Month",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "filter_date.keyword",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Actual", "id": "1", "settings": { "missing": "0" }, "type": "sum" },
      { "field": "Budget", "id": "8", "settings": { "missing": "0" }, "type": "sum" },
      { "field": "Forecast", "id": "9", "settings": { "missing": "0" }, "type": "sum" },
      { "field": "PremiumSupportFee", "id": "12", "settings": { "missing": "0" }, "type": "sum" },
      { "field": "SavingsPlanCost", "id": "13", "settings": { "missing": "0" }, "type": "sum" }
     ],
     "query": "Account.keyword: $Account AND CostCenter: $CostCenter AND CloudName: $CloudName AND filter_date.keyword: $Month",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Current Usage / $Account - Till Now \\ $Month",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Account.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Actual", "id": "1", "settings": { "missing": "0" }, "type": "sum" }
     ],
     "query": "(Account.keyword: $Account AND CostCenter: $CostCenter AND CloudName.keyword: $CloudName AND filter_date.keyword: $Month)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CY23 Budget / $Account",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Account.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "AllocatedBudget", "id": "1", "type": "max" }
     ],
     "query": "(Account.keyword: $Account AND CostCenter: $CostCenter AND CloudName.keyword: $CloudName)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ForeCasted next 12 M / $Account",
   "type": "barchart",
   "description": "IBM has only 1 current Month Forecast",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "Account.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "Forecast", "id": "1", "type": "sum" }
     ],
     "query": "(Account.keyword: $Account AND CostCenter: $CostCenter AND CloudName.keyword: $CloudName)",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}