pipeline {
    agent { label 'cloud-governance' }
    environment {
        AWS_ACCESS_KEY_ID = credentials('cloud-governance-aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('cloud-governance-aws-secret-access-key')
        BUCKET = credentials('cloud-governance-bucket')
        ES_HOST = credentials('cloud-governance-es-host')
    }
    stages {
        stage('Run all policies pre active region') {
            steps {
                 sh 'sudo podman pull quay.io/ebattat/cloud-governance'
                 sh 'sudo podman run --rm --name cloud-governance -e policy=ec2_idle -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -e AWS_DEFAULT_REGION=us-east-1 -e dry_run=yes -e policy_output=s3://${BUCKET}/logs/us-east-1 -e log_level=INFO quay.io/ebattat/cloud-governance'
                 sh 'echo ${AWS_ACCESS_KEY_ID}  ${AWS_SECRET_ACCESS_KEY}'
            }
        }
    }
    post {
        failure {
              script {
                msg = "Build error for ${env.JOB_NAME} ${env.BUILD_NUMBER} (${env.BUILD_URL})"
            }
          }
    }
}