pipeline {
    agent { label 'cloud-governance' }
    stages {
        stage('Run all policies pre active region') {
            steps {
                sh 'sudo podman images'
            }
        }
    }
    post {
        failure {
              script {
                msg = "Build error for ${env.JOB_NAME} ${env.BUILD_NUMBER} (${env.BUILD_URL})"

                slackSend message: msg, channel: env.SLACK_CHANNEL
            }
          }
    }
}