pipeline {
    agent {
        docker {
            label 'cloud-governance-worker'
            image 'quay.io/cloud-governance/fedora38-podman:latest'
            args  '-u root -v /etc/postfix/main.cf:/etc/postfix/main.cf --privileged'
        }
    }
    environment {
        QUAY_CLOUD_GOVERNANCE_REPOSITORY = credentials('QUAY_CLOUD_GOVERNANCE_REPOSITORY')
        AWS_ACCESS_KEY_ID_DELETE_PERF = credentials('cloud-governance-aws-access-key-id-delete-perf')
        AWS_SECRET_ACCESS_KEY_DELETE_PERF = credentials('cloud-governance-aws-secret-access-key-delete-perf')
        ES_HOST = credentials('cloud-governance-es-host')
        ES_PORT = credentials('cloud-governance-es-port')
        COST_SPREADSHEET_ID = credentials('cloud-governance-cost-spreadsheet-id')
        GOOGLE_APPLICATION_CREDENTIALS = credentials('cloud-governance-google-application-credentials')
        AWS_ACCOUNT_ROLE = credentials('cloud-governance-aws-account-role')
        COST_CENTER_OWNER = credentials('cloud-governance-cost-center-owner')
        REPLACE_ACCOUNT_NAME = credentials('cloud-governance-replace-account-names')
        PAYER_SUPPORT_FEE_CREDIT = credentials('cloud-governance-aws-payer-support-fee-credit')
        AWS_SECRET_ACCESS_KEY_ATHIRUMA_BOT = credentials('AWS_SECRET_ACCESS_KEY_ATHIRUMA_BOT')
        AWS_ACCESS_KEY_ID_ATHIRUMA_BOT = credentials('AWS_ACCESS_KEY_ID_ATHIRUMA_BOT')
        S3_RESULTS_PATH = credentials('S3_RESULTS_PATH')
        ATHENA_DATABASE_NAME = credentials('ATHENA_DATABASE_NAME')
        ATHENA_TABLE_NAME = credentials('ATHENA_TABLE_NAME')

        CLOUDABILITY_API = credentials('cloudability_api')
        CLOUDABILITY_API_REPORTS_PATH = credentials('cloudability_api_reports_path')
        CLOUDABILITY_METRICS = credentials('cloudability_metrics')
        CLOUDABILITY_VIEW_ID = credentials('cloudability_view_id')
        APPITO_KEY_ACCESS = credentials('appito_key_access')
        APPITO_KEY_SECRET = credentials('appito_key_secret')
        APPITO_ENVID = credentials('appito_envid')

        contact1 = "ebattat@redhat.com"
        contact2 = "yinsong@redhat.com"
        contact3 = "pragchau@redhat.com"
    }
    stages {
        stage('Checkout') { // Checkout (git clone ...) the projects repository
          steps {
            checkout scm
           }
        }
        stage('Initial Cleanup') {
            steps {
                 sh '''if [[ "$(podman images -q ${QUAY_CLOUD_GOVERNANCE_REPOSITORY} 2> /dev/null)" != "" ]]; then podman rmi -f $(podman images -q ${QUAY_CLOUD_GOVERNANCE_REPOSITORY} 2> /dev/null); fi'''
            }
        }
        stage('Run the AWS Cost Reports') {
            steps {
                sh 'python3 jenkins/clouds/aws/daily/org_cost_explorer/run_org_upload_es.py'
            }
        }
        stage('Finalize Cleanup') {
            steps {
                 sh '''if [[ "$(podman images -q ${QUAY_CLOUD_GOVERNANCE_REPOSITORY} 2> /dev/null)" != "" ]]; then podman rmi -f $(podman images -q ${QUAY_CLOUD_GOVERNANCE_REPOSITORY} 2> /dev/null); fi'''
                 deleteDir()
            }
        }
    }
    post {
       always {
           deleteDir()
       }
        failure {
              script {
                msg = "Build error for ${env.JOB_NAME} ${env.BUILD_NUMBER} (${env.BUILD_URL})"
                emailext body: """\
            Jenkins job: ${env.BUILD_URL}\nSee the console output for more details:  ${env.BUILD_URL}consoleFull\n\n
            """,
                subject: msg,
                to: "${contact1}, ${contact2}, ${contact3}"
            }
        }
    }
}
