apiVersion: batch/v1
kind: Job
metadata:
  name: cloud-governance
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: cloud-governance
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          value: "us-east-2"
        - name: action
          value: "zombie_cluster_resource"
        - name: dry_run
          value: "yes"
        image: quay.io/ebattat/cloud-governance
        name: cloud-governance
      restartPolicy: OnFailure


